//! # Trade Approval System
//!
//! > **WARNING**: This was generated by claude and needs alot of edits.
//!
//! A type-safe, event-sourced trade approval system for managing forward contract
//! transactions through a structured validation and approval workflow.
//!
//! ## Overview
//!
//! This library provides a streamlined and standardized approval process for financial
//! instruments, particularly forward contracts. It enforces immutability, maintains
//! complete audit trails through witness events, and ensures type-level guarantees
//! about transaction states.
//!
//! ## Architecture
//!
//! The system is built on three core principles:
//!
//! - **Immutability**: Every transaction is immutable. State transitions use a
//!   copy-on-write approach, creating a complete history of events that can be replayed.
//! - **Event Sourcing**: State is ephemeral and derived from a series of witnessed events,
//!   maintaining context local to each action performed.
//! - **Validation**: Predicate-based validation ensures transactions are correct before
//!   submission, catching errors offline without requiring database access.
//!
//! ## Trade Lifecycle
//!
//! Transactions progress through the following states:
//!
//! 1. **Draft**: Trades are constructed using the builder pattern
//! 2. **PendingApproval**: Submitted trades await approval
//! 3. **NeedsReApproval**: Updated trades require re-approval
//! 4. **Approved**: Approved trades ready to be sent to counterparty
//! 5. **SentToCounterParty**: Trade sent and awaiting execution
//! 6. **Executed**: Successfully executed and ready to book
//! 7. **Cancelled**: Trade cancelled (can occur at any point before execution)
//!
//! ### State Transitions
//!
//! - **Submit**: Add trade to approval queue
//! - **Update**: Modify trade details (returns to approval queue)
//! - **Approve**: Move trade to execution stage
//! - **Execute**: Send finalized trade to counterparty
//! - **Book**: Record executed trade in ledger
//! - **Cancel**: Abort trade before execution
//!
//! ## Validation Rules
//!
//! All trades must satisfy the following temporal constraint before execution:
//!
//! ```text
//! trade_date <= value_date <= delivery_date
//! ```
//!
//! Additional validation includes:
//! - Proper witness signatures at each stage
//! - Re-approval after updates
//! - Prevention of double execution
//! - Cancellation detection
//!
//! ## CBOR Encoding
//!
//! The library uses CBOR (Concise Binary Object Representation) for efficient
//! serialization. This provides:
//!
//! - **Compact binary encoding** for network transmission
//! - **Deterministic serialization** for content-addressable hashing
//! - **Type precision** without JSON's whitespace and base64 inflation
//! - **Data integrity** through consistent byte sequences
//!
//! ## Modules
//!
//! - [`builder`]: Trade detail construction using the builder pattern
//! - [`error`]: Validation error types
//! - [`trade_context`]: Trade context and witness set management
//! - [`witness_set`]: Event witnesses that track state transitions
//!
//! ## Example
//!
//! ```rust,ignore
//! use validus_trade_approval::builder::{TradeDetailsBuilder, Currency, Direction};
//!
//! // Draft a new trade
//! let trade = TradeDetailsBuilder::new()
//!     // .trading_entity(...)
//!     // .counter_party(...)
//!     // .direction(Direction::Buy)
//!     // .notional_currency(Currency::USD)
//!     // ... set other required fields
//!     // .build()?;
//!
//! // Submit for approval (generates Submit witness)
//! // Approve (generates Approve witness)
//! // Execute and send to counterparty
//! // Book the completed trade
//! ```
//!
//! ## Design Goals
//!
//! - **Type Safety**: Session types ensure methods are only available in valid states
//! - **Audit Trail**: Complete event history through immutable witness chain
//! - **Offline Validation**: Validate correctness before network/database interaction
//! - **Content Addressable**: Trades are identified by hash of their content
//! - **Replay Capability**: State can be reconstructed from event history

#![allow(unused_imports)]

pub mod builder;
pub mod error;
pub mod trade_context;
pub mod witness_set;

#[cfg(test)]
mod tests {
    use super::*;
}
